# Generated by Django 5.0.2 on 2024-02-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdCleanupApp', '0002_alter_pin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='zipcode',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
